30.03.2024 18-40-41 INFO "GET /sign/login/?next=/ HTTP/1.1" 200 2947 C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\servers\basehttp.py None
30.03.2024 18-40-41 INFO "GET /sign/login/?next=/ HTTP/1.1" 200 2947 C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\servers\basehttp.py None
12.04.2024 11-07-05 ERROR Internal Server Error: /accounts/signup/ C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\log.py (<class 'django.contrib.auth.models.Group.DoesNotExist'>, DoesNotExist('Group matching query does not exist.'), <traceback object at 0x000001CB99159380>)
Traceback (most recent call last):
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\decorators\debug.py", line 141, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\allauth\account\views.py", line 255, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\allauth\account\views.py", line 95, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\allauth\account\views.py", line 227, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\allauth\account\views.py", line 123, in post
    response = self.form_valid(form)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\allauth\account\views.py", line 269, in form_valid
    self.user, resp = form.try_save(self.request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\allauth\account\forms.py", line 403, in try_save
    user = self.save(request)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\sign\models.py", line 41, in save
    common_group = Group.objects.get(name='common')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\db\models\query.py", line 647, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
12.04.2024 11-07-05 ERROR "POST /accounts/signup/ HTTP/1.1" 500 151117 C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\servers\basehttp.py None
15.04.2024 14-31-49 ERROR Internal Server Error: /home/ C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002B6B5E87CC0>)
Traceback (most recent call last):
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\news\views.py", line 31, in get
    return HttpResponse(render(request, 'index.html', context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
15.04.2024 14-31-49 ERROR "GET /home/ HTTP/1.1" 500 102273 C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\servers\basehttp.py None
15.04.2024 14-32-01 ERROR Internal Server Error: /home/ C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002B6B609DC80>)
Traceback (most recent call last):
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\news\views.py", line 31, in get
    return HttpResponse(render(request, 'index.html', context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
15.04.2024 14-32-01 ERROR "GET /home/ HTTP/1.1" 500 102410 C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\servers\basehttp.py None
15.04.2024 14-32-01 ERROR Internal Server Error: /home/ C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002B6B5DF6700>)
Traceback (most recent call last):
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\news\views.py", line 31, in get
    return HttpResponse(render(request, 'index.html', context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
15.04.2024 14-32-01 ERROR "GET /home/ HTTP/1.1" 500 102410 C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\servers\basehttp.py None
15.04.2024 14-32-01 ERROR Internal Server Error: /home/ C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002B6B5EA3E40>)
Traceback (most recent call last):
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\news\views.py", line 31, in get
    return HttpResponse(render(request, 'index.html', context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
15.04.2024 14-32-01 ERROR "GET /home/ HTTP/1.1" 500 102410 C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\servers\basehttp.py None
15.04.2024 14-32-02 ERROR Internal Server Error: /home/ C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002B6B5CD2900>)
Traceback (most recent call last):
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\news\views.py", line 31, in get
    return HttpResponse(render(request, 'index.html', context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
15.04.2024 14-32-02 ERROR "GET /home/ HTTP/1.1" 500 102410 C:\Users\Splas\PycharmProjects\pythonProject12\NewsPortal\venv\Lib\site-packages\django\core\servers\basehttp.py None
